version: "3"

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="weMaintain"
    ports:
      - 27017:27017
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb